build:
  stage: build
  script:
    - docker build .
    - docker build push ${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_NAME}

tests:e2e:
  stage: tests
  script:
    - npm run docker:testing:up
    - npm run test:e2e

deploy:
  stage: deploy
  environment: production
  script: "echo 'TODO: add deploy job'"
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+$/'
