version: '3.7'

services:
  db:
    container_name: shop-api-db
    image: postgres:12.2-alpine
    env_file:
      - .env.dev
      - .env.local
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
