version: '3.7'

services:
  db:
    container_name: shop-api-db
    image: postgres:12.2-alpine
    env_file:
      - .env.dev
      - .env.local
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: app
